# Generated by Django 3.2.9 on 2022-02-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='parent',
        ),
    ]
